[project]
name = "SampleScraper"
version = "0.1.0"
description = "Web scraper for sample data aggregation."
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "cleo>=2.1.0",
    "requests>=2.32.3",
    "selenium>=4.32.0",
]
